// Auto-generated by apps/web/scripts/sync-bundled-themes.mjs
export type BundledTheme = {
  archiveName: string;
  archivePath: string;
  design: string;
  themeKey: string;
};

export const BUNDLED_THEMES: BundledTheme[] = [
  {
    "archiveName": "bundled-resume-themes-41d74bfc7de3.zip",
    "archivePath": "cdn/themes/bundled-resume-themes-41d74bfc7de3.zip",
    "design": "design:\n  theme: ahmadstyle\n",
    "themeKey": "ahmadstyle"
  },
  {
    "archiveName": "bundled-resume-themes-41d74bfc7de3.zip",
    "archivePath": "cdn/themes/bundled-resume-themes-41d74bfc7de3.zip",
    "design": "design:\n  theme: phdjakes\n",
    "themeKey": "phdjakes"
  },
  {
    "archiveName": "bundled-resume-themes-41d74bfc7de3.zip",
    "archivePath": "cdn/themes/bundled-resume-themes-41d74bfc7de3.zip",
    "design": "design:\n  theme: phddeedy\n",
    "themeKey": "phddeedy"
  },
  {
    "archiveName": "bundled-resume-themes-41d74bfc7de3.zip",
    "archivePath": "cdn/themes/bundled-resume-themes-41d74bfc7de3.zip",
    "design": "design:\n  theme: phdresearch\n",
    "themeKey": "phdresearch"
  },
  {
    "archiveName": "bundled-resume-themes-41d74bfc7de3.zip",
    "archivePath": "cdn/themes/bundled-resume-themes-41d74bfc7de3.zip",
    "design": "design:\n  theme: tylerstyle\n",
    "themeKey": "tylerstyle"
  }
];
