// Auto-generated by apps/web/scripts/sync-bundled-themes.mjs
export type BundledTheme = {
  archiveName: string;
  archivePath: string;
  design: string;
  themeKey: string;
};

export const BUNDLED_THEMES: BundledTheme[] = [
  {
    "archiveName": "ahzs645-resume-81fda66a90eb.zip",
    "archivePath": "cdn/themes/ahzs645-resume-81fda66a90eb.zip",
    "design": "design:\n  theme: ahmadstyle\n",
    "themeKey": "ahmadstyle"
  }
];
